apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  {{- if .Values.database.enabled }}
  database-password: {{ .Values.database.password | quote }}
  {{- end }}
  nextauth-url: {{ .Values.secrets.nextauthUrl | quote }}
  nextauth-secret: {{ .Values.secrets.nextauthSecret | quote }}
  discord-bot-token: {{ .Values.secrets.discordBotToken | quote }}
  admin-discord-user-id: {{ .Values.secrets.adminDiscordUserId | quote }}
  admin-email: {{ .Values.secrets.adminEmail | quote }}
  discord-client-id: {{ .Values.secrets.discordClientId | quote }}
  discord-client-secret: {{ .Values.secrets.discordClientSecret | quote }}
  discord-redirect-uri: {{ .Values.secrets.discordRedirectUri | quote }}
  discord-guild-id: {{ .Values.secrets.discordGuildId | quote }}
  stripe-secret-key: {{ .Values.secrets.stripeSecretKey | quote }}
  domain-name: {{ .Values.secrets.domainName | quote }}
  next-public-stripe-publishable-key: {{ .Values.secrets.nextPublicStripePublishableKey | quote }}
  next-public-api-url: {{ .Values.secrets.nextPublicApiUrl | quote }}
